#pragma once

/* Warning, this file is autogenerated by cbindgen from `src/redisearch_rs/c_entrypoint/bloom_filter_ffi/build.rs`. Don't modify it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque type BloomFilter. Can be instantiated with [`BloomFilter_New`].
 */
typedef struct BloomFilter BloomFilter;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new [`BloomFilter`]. Returns an opaque pointer to the newly created filter.
 *
 * # Arguments
 *
 * * `expected_items` - Expected number of unique items to be inserted
 * * `false_positive_rate` - Desired false positive rate (e.g., 0.01 for 1%)
 *
 * To free the filter, use [`BloomFilter_Free`].
 *
 * # Safety
 *
 * The following invariants must be upheld when calling this function:
 * - `expected_items` must be greater than 0
 * - `false_positive_rate` must be between 0.0 and 1.0 (exclusive)
 */
struct BloomFilter *BloomFilter_New(uintptr_t expected_items, double false_positive_rate);

/**
 * Insert an item into the Bloom filter.
 *
 * # Safety
 *
 * The following invariants must be upheld when calling this function:
 * - `filter` must point to a valid BloomFilter obtained from [`BloomFilter_New`] and cannot be NULL.
 * - `item` can be NULL only if `len == 0`. It is not necessarily NULL-terminated.
 * - `len` can be 0. If so, `item` is regarded as an empty string.
 */
void BloomFilter_Insert(struct BloomFilter *filter,
                        const char *item,
                        uintptr_t len);

/**
 * Check if an item might be in the Bloom filter.
 *
 * Returns 1 if the item might be in the set (with possible false positives),
 * or 0 if the item is definitely not in the set.
 *
 * # Safety
 *
 * The following invariants must be upheld when calling this function:
 * - `filter` must point to a valid BloomFilter obtained from [`BloomFilter_New`] and cannot be NULL.
 * - `item` can be NULL only if `len == 0`. It is not necessarily NULL-terminated.
 * - `len` can be 0. If so, `item` is regarded as an empty string.
 */
int BloomFilter_Contains(const struct BloomFilter *filter,
                         const char *item,
                         uintptr_t len);

/**
 * Get the number of items inserted into the filter.
 *
 * # Safety
 *
 * The following invariants must be upheld when calling this function:
 * - `filter` must point to a valid BloomFilter obtained from [`BloomFilter_New`] and cannot be NULL.
 */
uintptr_t BloomFilter_Count(const struct BloomFilter *filter);

/**
 * Get the memory usage of the filter in bytes.
 *
 * # Safety
 *
 * The following invariants must be upheld when calling this function:
 * - `filter` must point to a valid BloomFilter obtained from [`BloomFilter_New`] and cannot be NULL.
 */
uintptr_t BloomFilter_MemUsage(const struct BloomFilter *filter);

/**
 * Free the Bloom filter.
 *
 * # Safety
 *
 * The following invariants must be upheld when calling this function:
 * - `filter` must point to a valid BloomFilter obtained from [`BloomFilter_New`].
 * - `filter` can be NULL, in which case this function does nothing.
 * - After calling this function, `filter` must not be used again.
 */
void BloomFilter_Free(struct BloomFilter *filter);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
