#ifndef DATETIME_H
#define DATETIME_H

#pragma once

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace ffi {
#endif  // __cplusplus

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Parse an ISO-8601 formatted string into a Unix timestamp.
//
// # Arguments
//
// * `str` - A null-terminated C string containing an ISO-8601 date or datetime
// * `out_timestamp` - Pointer to store the resulting Unix timestamp (seconds since epoch)
//
// # Returns
//
// * `0` on success, with the timestamp written to `out_timestamp`
// * `-1` on error (invalid format or null pointer)
//
// # Safety
//
// The following invariants must be upheld when calling this function:
// - `str` must be a valid null-terminated C string or NULL
// - `out_timestamp` must be a valid pointer to an `i64` or NULL
// - If `str` or `out_timestamp` is NULL, the function returns -1
//
// # Examples
//
// ```c
// int64_t timestamp;
// int result = DateTime_ParseISO8601("2024-03-15T10:30:00Z", &timestamp);
// if (result == 0) {
//     printf("Timestamp: %lld\n", timestamp);
// }
// ```
int ParseISO8601(const char *str, int64_t *out_timestamp);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace ffi
#endif  // __cplusplus

#endif  /* DATETIME_H */
