#pragma once

/* Warning, this file is autogenerated by cbindgen from `src/redisearch_rs/c_entrypoint/query_cache_ffi/build.rs`. Don't modify it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque type for passing `QueryCache` across FFI boundary.
 */
typedef struct QueryCache {
  uint8_t _private[0];
} QueryCache;

/**
 * C-compatible cache statistics structure.
 */
typedef struct QueryCacheStats {
  uint64_t lookups;
  uint64_t hits;
  uint64_t misses;
  uint64_t evictions;
  size_t entries;
  size_t memory_bytes;
  double hit_rate;
} QueryCacheStats;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new query cache with the specified maximum number of entries.
 *
 * Returns a pointer to the cache that must be freed with `QueryCache_Free`.
 *
 * # Safety
 *
 * The returned pointer must be freed exactly once using `QueryCache_Free`.
 */
struct QueryCache *QueryCache_New(size_t max_entries);

/**
 * Free a query cache.
 *
 * # Safety
 *
 * - `cache` must have been created by `QueryCache_New`
 * - `cache` must not be null
 * - `cache` must not be used after this call
 */
void QueryCache_Free(struct QueryCache *cache);

/**
 * Get a cached result.
 *
 * Returns a pointer to the cached data and sets `size_out` to the data size.
 * Returns null if the key is not in the cache.
 *
 * The returned pointer is valid until the cache is modified or freed.
 *
 * # Safety
 *
 * - `cache` must have been created by `QueryCache_New`
 * - `cache` must not be null
 * - `size_out` must be a valid pointer
 */
const uint8_t *QueryCache_Get(struct QueryCache *cache,
                              uint64_t query_hash,
                              uint64_t index_revision,
                              size_t *size_out);

/**
 * Insert a result into the cache.
 *
 * # Safety
 *
 * - `cache` must have been created by `QueryCache_New`
 * - `cache` must not be null
 * - `data` must be a valid pointer to `data_size` bytes
 */
void QueryCache_Insert(struct QueryCache *cache,
                       uint64_t query_hash,
                       uint64_t index_revision,
                       const uint8_t *data,
                       size_t data_size);

/**
 * Clear all entries from the cache.
 *
 * # Safety
 *
 * - `cache` must have been created by `QueryCache_New`
 * - `cache` must not be null
 */
void QueryCache_Clear(struct QueryCache *cache);

/**
 * Resize the cache to a new maximum number of entries.
 *
 * # Safety
 *
 * - `cache` must have been created by `QueryCache_New`
 * - `cache` must not be null
 */
void QueryCache_Resize(struct QueryCache *cache, size_t new_max_entries);

/**
 * Get cache statistics.
 *
 * # Safety
 *
 * - `cache` must have been created by `QueryCache_New`
 * - `cache` must not be null
 */
struct QueryCacheStats QueryCache_GetStats(const struct QueryCache *cache);

/**
 * Reset statistics counters (but keep cached entries).
 *
 * # Safety
 *
 * - `cache` must have been created by `QueryCache_New`
 * - `cache` must not be null
 */
void QueryCache_ResetStats(struct QueryCache *cache);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
