#pragma once

/* Warning, this file is autogenerated by cbindgen from `src/redisearch_rs/c_entrypoint/sql_parser_ffi/build.rs`. Don't modify it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Command type for the translation result.
 */
typedef enum SqlCommand {
  /**
   * Use FT.SEARCH for this query.
   */
  Search = 0,
  /**
   * Use FT.AGGREGATE for this query.
   */
  Aggregate = 1,
  /**
   * Use FT.HYBRID for weighted vector + text search.
   */
  Hybrid = 2,
} SqlCommand;

/**
 * Result structure for SQL to RQL translation.
 *
 * On success:
 * - `success` is true
 * - `command` indicates whether to use FT.SEARCH or FT.AGGREGATE
 * - `index_name` contains the index name (must be freed)
 * - `query_string` contains the RQL query (must be freed)
 * - `arguments` contains additional arguments (must be freed)
 * - `arguments_len` is the number of arguments
 * - `error_message` is null
 *
 * On failure:
 * - `success` is false
 * - `error_message` contains the error description (must be freed)
 * - Other fields are zeroed/null
 */
typedef struct SqlTranslationResult {
  /**
   * Whether the translation succeeded.
   */
  bool success;
  /**
   * The command type (0 = Search, 1 = Aggregate).
   */
  enum SqlCommand command;
  /**
   * The index name from the FROM clause. Null on error.
   */
  char *index_name;
  /**
   * The RQL query string. Null on error.
   */
  char *query_string;
  /**
   * Array of additional arguments (RETURN, SORTBY, LIMIT, etc.). Null on error.
   */
  char **arguments;
  /**
   * Number of elements in the arguments array.
   */
  size_t arguments_len;
  /**
   * Error message if translation failed. Null on success.
   */
  char *error_message;
} SqlTranslationResult;

/**
 * Schema capabilities for a single field supplied by the C caller.
 */
typedef struct SqlSchemaField {
  /**
   * Field name as a null-terminated UTF-8 string.
   */
  const char *name;
  /**
   * Whether exact TAG-style matching is supported.
   */
  bool supports_tag_queries;
  /**
   * Whether TEXT query semantics are supported.
   */
  bool supports_text_queries;
  /**
   * Whether the field indexes missing values.
   */
  bool supports_index_missing;
} SqlSchemaField;

/**
 * Cache statistics returned by `sql_cache_get_stats`.
 */
typedef struct SqlCacheStats {
  /**
   * Number of entries currently in the cache.
   */
  size_t entries;
  /**
   * Total number of cache hits.
   */
  uint64_t hits;
  /**
   * Total number of cache misses.
   */
  uint64_t misses;
  /**
   * Hit rate as an integer percentage (0-100).
   */
  uint32_t hit_rate_percent;
} SqlCacheStats;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Translates a SQL query to RQL format.
 *
 * # Safety
 *
 * - `sql` must point to `sql_len` readable bytes for the duration of this call.
 * - `sql` must contain valid UTF-8 and no embedded NUL bytes.
 * - The returned `SqlTranslationResult` must be freed with `sql_translation_result_free`
 */
struct SqlTranslationResult sql_translate(const uint8_t *sql, size_t sql_len);

/**
 * Frees a `SqlTranslationResult` returned by `sql_translate`.
 *
 * # Safety
 *
 * - `result` must have been returned by `sql_translate`
 * - `result` must not be used after calling this function
 * - This function must be called exactly once per result
 */
void sql_translation_result_free(struct SqlTranslationResult result);

/**
 * Translates a SQL query to RQL format with caching.
 *
 * This function caches translation results, so repeated calls with the same
 * SQL string will return cached results (improving performance).
 *
 * # Safety
 *
 * - `sql` must point to `sql_len` readable bytes for the duration of this call.
 * - `sql` must contain valid UTF-8 and no embedded NUL bytes.
 * - The returned `SqlTranslationResult` must be freed with `sql_translation_result_free`
 */
struct SqlTranslationResult sql_translate_cached(const uint8_t *sql, size_t sql_len);

/**
 * Translates a SQL query to RQL format with schema-aware caching.
 *
 * The cache key includes the provided schema version, and the supplied field
 * capabilities are used to validate exact string matching semantics.
 *
 * # Safety
 *
 * - `sql` must point to `sql_len` readable bytes for the duration of this call.
 * - `sql` must contain valid UTF-8 and no embedded NUL bytes.
 * - If `fields_len > 0`, then `fields` must point to `fields_len` valid elements.
 * - Each `SqlSchemaField.name` must be a valid null-terminated UTF-8 string.
 * - The returned `SqlTranslationResult` must be freed with `sql_translation_result_free`.
 */
struct SqlTranslationResult sql_translate_cached_with_schema(const uint8_t *sql,
                                                             size_t sql_len,
                                                             uint64_t schema_version,
                                                             const struct SqlSchemaField *fields,
                                                             size_t fields_len);

/**
 * Clear the SQL translation cache.
 *
 * This removes all cached translations and resets hit/miss statistics.
 */
void sql_cache_clear(void);

/**
 * Get SQL cache statistics.
 *
 * Returns current cache state including entry count, hits, misses, and hit rate.
 */
struct SqlCacheStats sql_cache_get_stats(void);

/**
 * Set the maximum number of entries in the SQL translation cache.
 *
 * If the new limit is smaller than the current number of entries,
 * the least recently used entries are evicted.
 */
void sql_cache_set_max_entries(size_t max_entries);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
